### ISSUE TITLE
Python script to call a Scala job?

### ISSUE THREAD

**Issue by angelcervera** [EqualExperts/data-engineering-exercise-scala#1]
The README says:
> Your program will be invoked with pipenv run python src/main.py /path/to/posts_file.json /path/to/votes_file.json

Does it mean that the solution is in Scala, but it should be invocated from a Python script?

**Comment by cdiniz** [comment]
Hi @angelcervera. 
Thank you for your time to give us feedback, the README is updated accordingly.
